id: P004173
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:58:16.353988
source_metadata:
  id: bdr:W20455
  title: དབུ་མ་རྩ་བ་ཤེས་རབ་རྩ་འགྲེལ།
  author: ''
  volumes:
    230190328d4c45fc850b73c5ed655766:
      image_group_id: I1KG10511
      title: ''
      volume_number: 1
      total_pages: 511
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
