id: P004173
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W20455
  title: དབུ་མ་རྩ་བ་ཤེས་རབ་རྩ་འགྲེལ།
  author: ''
  volumes:
    230190328d4c45fc850b73c5ed655766:
      image_group_id: I1KG10511
      title: ''
      volume_number: 1
      total_pages: 511
      base_file: v001.txt
